
services:
  
  webserver_apache:
    image: httpd:alpine
    
  
  webserver_nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
  webserver_caddy:
    image: caddy:alpine
    ports:
      - "8081:80"
  
  tester_fortio:
    image: fortio/fortio 
    depends_on:
      - webserver_apache
      - webserver_caddy
      - webserver_nginx
    volumes:
      - ./data/:/data/
    entrypoint: /data/run.sh
  
  
